import React, { useEffect } from "react";
import { withFirebase } from "../Firebase";
import "firebase/auth";
import "firebase/database";
import "firebase/storage";

const ApiFetcher = (props) => {
  useEffect(() => {
    const interval = setInterval(() => {
      //setinterval with a clearinterval at the bottom, so it doesn't re-render itself because of useEffect.
      let userCardId = null;
      let userMainId = null;
      let userBuyPoint = null;

      props.firebase
        .cards()
        .once("value")
        .then((snapshot) => {
          // catch a snapshot of the firebase database, but only once, which doesn't let it loop itself.
          const cardObject = snapshot.val();

          const cardList = Object.keys(cardObject).map((key) => ({
            ...cardObject[key],
          }));
          userCardId = cardList.map((card) => card.cardId); // Every card if of every user, these ids are generated by the yugioh api and fetched from our firebase.
          userMainId = Object.keys(cardObject); // The IDs of the users card, fetched from firebase, generated by firebase, which is where the delta is stored
          userBuyPoint = cardList.map((card) => card.buy_point); // The buypoint value of each card which the user has put in, fetched from firebase.
          async function cardCalculator() {
            // aysnc func that lets you wait for the api response before calculating values.
            for (
              let k = 0;
              k < userBuyPoint.length;
              k++ // Loop which matches usercards to yugioh api, and checks for price difference, if there is one, pushes the delta to firebase
            ) {
              var url =
                "https://db.ygoprodeck.com/api/v7/cardinfo.php?id=" +
                userCardId[k];

              const response = await fetch(url);
              var apiCardData = await response.json();
              let cardSetObject = apiCardData.data[0].card_sets.find(
                (item) => item.set_code === cardList[k].cardSet.set_code
              );
              var apiCardPrice = cardSetObject.set_price;
              //gör en check för setprice
              //gör en .find() och plocka ut set_price-objektet
              //ta det objektet och matcha set-kod
              //

              // console.log(cardList[k].cardSet.set_code);

              // console.log(cardSetObject.set_price);
              // console.log(apiCardPrice + " <----- detta är apicardprice");
              if (
                userBuyPoint[k] < apiCardPrice ||
                userBuyPoint[k] > apiCardPrice
              ) {
                var delta = apiCardPrice - userBuyPoint[k];
                //kör nedanstående endast om den senaste
                props.firebase
                  .card(userMainId[k])
                  .child("priceChangeDeltaValueHistory")
                  .child(+new Date())
                  .set(delta);
                // console.log("batch: "+ new Date());
              }
            }
          }
          cardCalculator();
        });
    }, 60000); /* <- the interval at which this runs, in milliseconds */
    return () => clearInterval(interval);
  }, [props.firebase]);

  return <div></div>;
};

const ApiFetch = withFirebase(ApiFetcher);
export default ApiFetch;
