import React, { useEffect, useState } from "react";
import { withFirebase } from "../Firebase";
import 'firebase/auth'
import 'firebase/database'
import 'firebase/storage'

const ApiFetcher = (props) => {
    const [UCid, setUCid] = useState(null);

    
    useEffect(() => {
        const interval = setInterval (() => { //setinterval with a clearinterval at the bottom, so it doesn't re-render itself because of useEffect.
        let userCardId = null;
        let userMainId = null;
        let userBuyPoint = null;
        let k = null;
        
        props.firebase.cards().once('value').then((snapshot) => { // catch a snapshot of the firebase database, but only once, which doesn't let it loop itself.
            const cardObject = snapshot.val();
            
            const cardList = Object.keys(cardObject).map((key) => ({
                ...cardObject[key]
            }));
            userCardId = cardList.map(card => card.cardId); // The card ids of each user, these ids are generated by the yugioh api and fetched from our firebase.
            userMainId = Object.keys(cardObject);    // The IDs of the users, fetched from firebase, generated by firebase.        
            userBuyPoint = cardList.map(card => card.buy_point); // The buypoint value of each card which the user has put in, fetched from firebase.
            async function cardCalculator (){ // aysnc func that lets you wait for the api response before calculating values.
            for(k = 0; k < userBuyPoint.length; k++) // Loop which matches usercards to yugioh api, and checks for price difference, if there is one, pushes to firebase.
            {   
                
                var url = "https://db.ygoprodeck.com/api/v7/cardinfo.php?id=" + userCardId[k]
                
                const response = await fetch(url);
                var apiCardData = await   response.json();
                var apiCardPrice = apiCardData.data[0].card_prices[0].cardmarket_price;
                if(userBuyPoint[k] < apiCardPrice || userBuyPoint[k] > apiCardPrice)
                {
                    var delta = apiCardPrice - userBuyPoint[k];
                props.firebase.card(userMainId[k]).child('priceChangeDeltaValueHistory').child(+ new Date).set(delta);
                console.log("test batch: "+ new Date);
                }
            }

            }

            cardCalculator();
    
          });

          
    }, 300000);
    return () => clearInterval(interval);
        
        
        


    }, [props.firebase])


    return (
        <div>
            
        </div>
    )
}

const ApiFetch = withFirebase(ApiFetcher);
export default ApiFetch;
